In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [ ]:
print(x.dtype)

torch.int64


In [ ]:
print(type(x))
print(x.type())

<class 'torch.Tensor'>
torch.LongTensor


In [ ]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [ ]:
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4])


In [ ]:
data = np.array([1,2,3])

In [ ]:
a = torch.Tensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [ ]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3]) torch.LongTensor


In [ ]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


In [ ]:
x = torch.empty(4, 3)
print(x)

tensor([[6.9494e-34, 0.0000e+00, 7.5807e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [ ]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


In [ ]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


In [ ]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


In [ ]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


In [ ]:
print('Old:', x.type())
x = x.type(torch.int64)
print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


In [ ]:
x = torch.rand(4, 3)
print(x)

tensor([[0.2824, 0.7406, 0.2184],
        [0.8592, 0.9238, 0.1251],
        [0.3230, 0.8697, 0.7179],
        [0.6968, 0.3891, 0.2441]])


In [ ]:
x = torch.randn(4, 3)
print(x)

tensor([[ 0.4836,  0.4532, -0.1742],
        [ 0.6775,  1.7129, -0.1954],
        [-0.4653, -1.7410,  0.5757],
        [ 0.0926, -0.4760, -0.3839]])


In [ ]:
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[2, 3, 2],
        [2, 2, 0],
        [2, 2, 0],
        [3, 0, 3]])


In [ ]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.1676,  0.9762,  0.9238, -0.3377,  1.5602],
        [-0.4162, -0.9282, -0.3636,  1.0434, -1.2198]])


In [ ]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x.size()

torch.Size([2, 3])

In [ ]:
x.device

device(type='cpu')

In [ ]:
x.layout

torch.strided